### ISSUE TITLE
v1.0.0 release checklist

### ISSUE THREAD

**Issue by averycrespi** [averycrespi/thinktank#20]
- [x] Final tweaks and playtesting
- [x] Update `package.json` version
- [x] Merge develop into master
- [x] Publish v1.0.0 to NPM
- [x] Publish GitHub release
- [x] Send project PR to boardgame.io
